language: java
jdk: oraclejdk8
before_install:
  - (cd ~; curl -sLo - https://github.com/github/git-lfs/releases/download/v1.1.1/git-lfs-linux-amd64-1.1.1.tar.gz | tar xzvf -)
install:
  - (git clone https://github.com/chopshop-166/wpilib-mirror.git -b lfs ~/wpilib && cd ~/wpilib && ~/git-lfs-*/git-lfs pull)
script: ant jar
